# Deep learning classification model 

In [1]:
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np

Using TensorFlow backend.


# Dataset

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Soybean.csv',header=None,skiprows=[0])
print(df.head())

                      0    1    2    3    4    5    6    7    8    9   ...  \
0  diaporthe-stem-canker  6.0  0.0  2.0  1.0  0.0  1.0  1.0  1.0  0.0  ...   
1  diaporthe-stem-canker  4.0  0.0  2.0  1.0  0.0  2.0  0.0  2.0  1.0  ...   
2  diaporthe-stem-canker  3.0  0.0  2.0  1.0  0.0  1.0  0.0  2.0  1.0  ...   
3  diaporthe-stem-canker  3.0  0.0  2.0  1.0  0.0  1.0  0.0  2.0  0.0  ...   
4  diaporthe-stem-canker  6.0  0.0  2.0  1.0  0.0  2.0  0.0  1.0  0.0  ...   

    26   27   28   29   30   31   32   33   34   35  
0  0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 36 columns]


In [3]:
df[0].value_counts()

brown-spot                     92
frog-eye-leaf-spot             91
alternarialeaf-spot            91
phytophthora-rot               88
anthracnose                    44
brown-stem-rot                 44
downy-mildew                   20
diaporthe-stem-canker          20
purple-seed-stain              20
bacterial-blight               20
charcoal-rot                   20
bacterial-pustule              20
rhizoctonia-root-rot           20
powdery-mildew                 20
phyllosticta-leaf-spot         20
2-4-d-injury                   16
diaporthe-pod-&-stem-blight    15
cyst-nematode                  14
herbicide-injury                8
Name: 0, dtype: int64

# categorising targets

In [4]:
target=pd.get_dummies(df.iloc[:,0],drop_first=True).values
print(target[:10])

[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]]


In [5]:
predictors=df.drop(0,axis=1).values
print(predictors[:7])
n_cols=predictors.shape[1]

[[6. 0. 2. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 2. 2. 0. 0. 0. 1. 1. 3. 1. 1. 1.
  0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [4. 0. 2. 1. 0. 2. 0. 2. 1. 1. 1. 1. 0. 2. 2. 0. 0. 0. 1. 0. 3. 1. 1. 1.
  0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [3. 0. 2. 1. 0. 1. 0. 2. 1. 2. 1. 1. 0. 2. 2. 0. 0. 0. 1. 0. 3. 0. 1. 1.
  0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [3. 0. 2. 1. 0. 1. 0. 2. 0. 1. 1. 1. 0. 2. 2. 0. 0. 0. 1. 0. 3. 0. 1. 1.
  0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [6. 0. 2. 1. 0. 2. 0. 1. 0. 2. 1. 1. 0. 2. 2. 0. 0. 0. 1. 0. 3. 1. 1. 1.
  0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [5. 0. 2. 1. 0. 3. 0. 1. 0. 1. 1. 1. 0. 2. 2. 0. 0. 0. 1. 0. 3. 0. 1. 1.
  0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [5. 0. 2. 1. 0. 2. 0. 1. 1. 0. 1. 1. 0. 2. 2. 0. 0. 0. 1. 1. 3. 1. 1. 1.
  0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]]


# Instantiating the model,adding hidden and output layer.

In [6]:
model=Sequential()
model.add(Dense(5,activation='relu',input_shape=(n_cols,)))
model.add(Dense(5,activation='relu'))
model.add(Dense(5,activation='relu'))
model.add(Dense(18,activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


# Compiling and fitting the model

In [7]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.fit(predictors,target,epochs=100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
683/683 [==============================] - 1s 898us/step - loss: nan - acc: 0.1523
Epoch 2/100
683/683 [==============================] - 0s 65us/step - loss: nan - acc: 0.1567
Epoch 3/100
683/683 [==============================] - 0s 57us/step - loss: nan - acc: 0.1567
Epoch 4/100
683/683 [==============================] - 0s 57us/step - loss: nan - acc: 0.1567
Epoch 5/100
683/683 [==============================] - 0s 65us/step - loss: nan - acc: 0.1567
Epoch 6/100
683/683 [==============================] - 0s 67us/step - loss: nan - acc: 0.1567
Epoch 7/100
683/683 [==============================] - 0s 67us/step - loss: nan - acc: 0.1567
Epoch 8/100
683/683 [==============================] - 0s 69us/step - loss: nan - acc: 0.1567
Epoch 9/100
683/683 [==============================] - 0s 73us/step - loss: nan - acc: 0.1567
Epoch 10/100
683/683 [==============================] - 0s 63us/step - loss: nan - acc: 0.1567
Epoch 11/1

683/683 [==============================] - 0s 97us/step - loss: nan - acc: 0.1567
Epoch 85/100
683/683 [==============================] - 0s 103us/step - loss: nan - acc: 0.1567
Epoch 86/100
683/683 [==============================] - 0s 96us/step - loss: nan - acc: 0.1567
Epoch 87/100
683/683 [==============================] - 0s 78us/step - loss: nan - acc: 0.1567
Epoch 88/100
683/683 [==============================] - 0s 92us/step - loss: nan - acc: 0.1567
Epoch 89/100
683/683 [==============================] - 0s 89us/step - loss: nan - acc: 0.1567
Epoch 90/100
683/683 [==============================] - 0s 85us/step - loss: nan - acc: 0.1567
Epoch 91/100
683/683 [==============================] - 0s 95us/step - loss: nan - acc: 0.1567
Epoch 92/100
683/683 [==============================] - 0s 77us/step - loss: nan - acc: 0.1567
Epoch 93/100
683/683 [==============================] - 0s 82us/step - loss: nan - acc: 0.1567
Epoch 94/100
683/683 [==============================] - 0s 75u

# Adding validation split

In [12]:
model.fit(predictors,target,epochs=100,validation_split=0.2)

Train on 546 samples, validate on 137 samples
Epoch 1/100
546/546 [==============================] - 0s 74us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 2/100
546/546 [==============================] - 0s 72us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 3/100
546/546 [==============================] - 0s 93us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 4/100
546/546 [==============================] - 0s 88us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 5/100
546/546 [==============================] - 0s 86us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 6/100
546/546 [==============================] - 0s 102us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 7/100
546/546 [==============================] - 0s 85us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 8/100
546/546 [==============================] - 0s

546/546 [==============================] - 0s 83us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 65/100
546/546 [==============================] - 0s 72us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 66/100
546/546 [==============================] - 0s 79us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 67/100
546/546 [==============================] - 0s 67us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 68/100
546/546 [==============================] - 0s 70us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 69/100
546/546 [==============================] - 0s 85us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 70/100
546/546 [==============================] - 0s 70us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 71/100
546/546 [==============================] - 0s 85us/step - loss: nan - acc: 0.0769 - val_loss: nan

# Adding Callbacks

In [14]:
from keras.callbacks import EarlyStopping
early_stopping_monitor=EarlyStopping(patience=2)

In [16]:
model.fit(predictors,target,validation_split=0.2,callbacks=[early_stopping_monitor],epochs=30)

Train on 546 samples, validate on 137 samples
Epoch 1/30
546/546 [==============================] - 0s 78us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
Epoch 2/30
546/546 [==============================] - 0s 95us/step - loss: nan - acc: 0.0769 - val_loss: nan - val_acc: 0.4745
